version: '2'

networks:
  recipe-network:

volumes:
  recipe-database-data:

services:
  app:
    container_name: recipe_book_app
    build: ./recipebook-service
    networks:
      - recipe-network
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER_NAME=postgres
      - DB_PASSWORD=root

  db:
    container_name: recipe_book_pg_db
    build: ./postgres
    volumes:
      - recipe-database-data:/var/lib/postgresql/data
    networks:
      - recipe-network
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=recipe_book